# generated by datamodel-codegen:
#   filename:  buttonReq.json
#   timestamp: 2024-10-05T23:21:02+00:00

from __future__ import annotations

from pydantic import BaseModel


class GetButton(BaseModel):
    url: str
    id: str
    label: str
    css_class: str
