# generated by datamodel-codegen:
#   filename:  componentResponse.json
#   timestamp: 2024-10-06T07:05:14+00:00

from __future__ import annotations

from pydantic import BaseModel


class ComponentResponse(BaseModel):
    html: str
