# generated by datamodel-codegen:
#   filename:  getNav.json
#   timestamp: 2024-10-06T08:09:22+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class ListItem(BaseModel):
    active: bool
    url: str
    label: str
    icon: str


class GetNav(BaseModel):
    title: str
    listItems: List[ListItem]
